version: "3.1"

services:
   psql:
     image: postgres
     secrets:
       - texty
       - textyy
     environment:
       POSTGRES_PASSWORD_FILE: C:\Users\michael.kourbelis\Desktop\secrets\texty
       POSTGRES_USER_FILE: C:\Users\michael.kourbelis\Desktop\secrets\textyy
secrets:
  texty:
      file: ./texty.txt
  textyy:
       file: ./textyy.txt